// Generated by gencpp from file rosfalcon/falconSetPoint.msg
// DO NOT EDIT!


#ifndef ROSFALCON_MESSAGE_FALCONSETPOINT_H
#define ROSFALCON_MESSAGE_FALCONSETPOINT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rosfalcon
{
template <class ContainerAllocator>
struct falconSetPoint_
{
  typedef falconSetPoint_<ContainerAllocator> Type;

  falconSetPoint_()
    : X(0.0)
    , Y(0.0)
    , Z(0.0)  {
    }
  falconSetPoint_(const ContainerAllocator& _alloc)
    : X(0.0)
    , Y(0.0)
    , Z(0.0)  {
  (void)_alloc;
    }



   typedef double _X_type;
  _X_type X;

   typedef double _Y_type;
  _Y_type Y;

   typedef double _Z_type;
  _Z_type Z;




  typedef boost::shared_ptr< ::rosfalcon::falconSetPoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rosfalcon::falconSetPoint_<ContainerAllocator> const> ConstPtr;

}; // struct falconSetPoint_

typedef ::rosfalcon::falconSetPoint_<std::allocator<void> > falconSetPoint;

typedef boost::shared_ptr< ::rosfalcon::falconSetPoint > falconSetPointPtr;
typedef boost::shared_ptr< ::rosfalcon::falconSetPoint const> falconSetPointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rosfalcon::falconSetPoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rosfalcon::falconSetPoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rosfalcon

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'rosfalcon': ['/home/dong/Project/rosfalcon/src/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rosfalcon::falconSetPoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rosfalcon::falconSetPoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosfalcon::falconSetPoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosfalcon::falconSetPoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosfalcon::falconSetPoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosfalcon::falconSetPoint_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rosfalcon::falconSetPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8219583d7802cc50be3e9ab911877ba5";
  }

  static const char* value(const ::rosfalcon::falconSetPoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8219583d7802cc50ULL;
  static const uint64_t static_value2 = 0xbe3e9ab911877ba5ULL;
};

template<class ContainerAllocator>
struct DataType< ::rosfalcon::falconSetPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rosfalcon/falconSetPoint";
  }

  static const char* value(const ::rosfalcon::falconSetPoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rosfalcon::falconSetPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 X\n\
float64 Y\n\
float64 Z\n\
";
  }

  static const char* value(const ::rosfalcon::falconSetPoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rosfalcon::falconSetPoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.X);
      stream.next(m.Y);
      stream.next(m.Z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct falconSetPoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rosfalcon::falconSetPoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rosfalcon::falconSetPoint_<ContainerAllocator>& v)
  {
    s << indent << "X: ";
    Printer<double>::stream(s, indent + "  ", v.X);
    s << indent << "Y: ";
    Printer<double>::stream(s, indent + "  ", v.Y);
    s << indent << "Z: ";
    Printer<double>::stream(s, indent + "  ", v.Z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSFALCON_MESSAGE_FALCONSETPOINT_H
